name: gosec
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  security-events: write

jobs:
  gosec:
    name: security scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: stable
      - name: Run Gosec Security Scanner
        uses: securego/gosec@9e75c0576c9878035d4221392108d458abe10fc3 # v2.28.0
        with:
          args: "-no-fail -fmt json -out results.json ./..."

      - name: Check Gosec Results
        run: |
          FOUND=$(jq '.Stats.found // 0' results.json)
          echo "Gosec found $FOUND issue(s)"
          if [ "$FOUND" -gt 0 ]; then
            echo "❌ Security issues detected! Please fix them before merging."
            exit 1
          else
            echo "✅ No security issues found."
          fi

      - name: Run zizmor 🌈
        uses: zizmorcore/zizmor-action@192e21d79ab29983730a13d1382995c2307fbcaa # v0.5.7
        with:
          inputs: .
          fail_on_error: true
